repos:
    - repo: https://github.com/psf/black
      rev: stable
      hooks:
          - id: black
            exclude: frontend, nginx
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.4
      hooks:
          - id: flake8
            exclude: frontend, nginx
