version: '3.9'

services:
    django:
        container_name: players_crm_django
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        env_file: ./.env
        depends_on:
            - postgres
            - celery
            - celery-beat
        volumes:
            - ./backend:/app
        networks:
            - db_net
            - app_net
        command: ./start.sh

    react:
        container_name: players_crm_react
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        volumes:
            - ./frontend:/app
        ports:
            - 3000:3000

    postgres:
        container_name: players_crm_postgres
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_NAME}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        env_file: ./.env
        networks:
            - db_net

    nginx:
        container_name: players_crm_nginx
        image: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - static_data:/app/static
        depends_on:
            - django
        ports:
            - 8080:8080
        networks:
            - app_net

    redis:
        container_name: players_crm_redis
        image: redis:alpine
        networks:
            - db_net

    celery:
        container_name: players_crm_celery
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        env_file: ./.env
        command: celery -A config worker -l info
        volumes:
            - ./backend/:/app:rw
        environment:
            - DEBUG=${DEBUG}
            - SECRET_KEY=${SECRET_KEY}
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        depends_on:
            - redis
            - postgres
        networks:
            - db_net

    celery-beat:
        container_name: players_crm_celery_beat
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        env_file: ./.env
        command: celery -A config beat -l info
        volumes:
            - ./backend/:/app:rw
        environment:
            - DEBUG=${DEBUG}
            - SECRET_KEY=${SECRET_KEY}
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        depends_on:
            - redis
            - postgres
        networks:
            - db_net

volumes:
    postgres_data:
    static_data:

networks:
    db_net:
    app_net:
