version: '3.9'

services:
    backend:
        build: ./backend
        env_file: ./.env
        depends_on:
            - db
        volumes:
            - static_data:/backend/static
        networks:
            - db_net
            - app_net

    frontend:
        build: ./frontend
        ports:
            - 3000:3000

    db:
        image: postgres
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_NAME}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        env_file: ./.env
        networks:
            - db_net

    gateway:
        image: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - static_data:/backend/static
        depends_on:
            - backend
        ports:
            - 8080:8080
        networks:
            - app_net

volumes:
    db_data:
    static_data:

networks:
    db_net:
    app_net:
