# Generated by Django 3.1.4 on 2021-01-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ChannelsStats",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_voice_channels", models.IntegerField()),
                ("occupied_voice_channels", models.IntegerField()),
                ("empty_voice_channels", models.IntegerField()),
                ("voice_channels_users", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UsersStats",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_users", models.IntegerField()),
                ("online_users", models.IntegerField()),
                ("offline_users", models.IntegerField()),
                ("activities", models.ManyToManyField(to="dashboards.Activity")),
            ],
        ),
        migrations.CreateModel(
            name="ServerStats",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "channels_stats",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_stats",
                        to="dashboards.channelsstats",
                    ),
                ),
                (
                    "users_stats",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_stats",
                        to="dashboards.usersstats",
                    ),
                ),
            ],
        ),
    ]
